apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-app
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: default-demo-app-strip@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
  - host: demo.lab.local
    http:
      paths:
      - path: /demo-app
        pathType: Prefix
        backend:
          service:
            name: demo-app
            port:
              number: 80
